// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOl9wwSTUK7OVZDotozKFJ-ZOCY4wuloo',
    appId: '1:2488750274:web:6083b72e2d68a1f53f6b5b',
    messagingSenderId: '2488750274',
    projectId: 'msosi-app-f9114',
    authDomain: 'msosi-app-f9114.firebaseapp.com',
    storageBucket: 'msosi-app-f9114.firebasestorage.app',
    measurementId: 'G-0VG1R3K6XH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8ASOkkCzGq6Aw9kFFU0xS4p8M5kSdW-w',
    appId: '1:2488750274:android:f4ce2554980194a23f6b5b',
    messagingSenderId: '2488750274',
    projectId: 'msosi-app-f9114',
    storageBucket: 'msosi-app-f9114.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClOshVBejkg90F6uSULV_7oTESziHCzog',
    appId: '1:2488750274:ios:f7dc9cc09ab49a3a3f6b5b',
    messagingSenderId: '2488750274',
    projectId: 'msosi-app-f9114',
    storageBucket: 'msosi-app-f9114.firebasestorage.app',
    iosClientId: '2488750274-nkcmpg6uu7l0g2q7mh0okb9cfegh55ro.apps.googleusercontent.com',
    iosBundleId: 'com.university.campusfood.campusFoodChatbot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClOshVBejkg90F6uSULV_7oTESziHCzog',
    appId: '1:2488750274:ios:f7dc9cc09ab49a3a3f6b5b',
    messagingSenderId: '2488750274',
    projectId: 'msosi-app-f9114',
    storageBucket: 'msosi-app-f9114.firebasestorage.app',
    iosClientId: '2488750274-nkcmpg6uu7l0g2q7mh0okb9cfegh55ro.apps.googleusercontent.com',
    iosBundleId: 'com.university.campusfood.campusFoodChatbot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOl9wwSTUK7OVZDotozKFJ-ZOCY4wuloo',
    appId: '1:2488750274:web:4de3d0ff469d76443f6b5b',
    messagingSenderId: '2488750274',
    projectId: 'msosi-app-f9114',
    authDomain: 'msosi-app-f9114.firebaseapp.com',
    storageBucket: 'msosi-app-f9114.firebasestorage.app',
    measurementId: 'G-1862391N1Z',
  );
}
